# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BdPl42DYrW6Emx21Dyb59TJVU4t0840h
"""

from google.colab import files
  
  
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import io


dataset=pd.read_csv(io.StringIO(uploaded['student_score.csv'].decode('utf-8')))
dataset.shape
(25,2)

dataset.head()
dataset.describe()

dataset.plot(x='Hours',y='Scores',style='.')

plt.title('Student Mark Prediction')

plt.xlabel('Hours')
plt.ylabel('Percentage Marks')

plt.show()

X=dataset.iloc[:,:-1].values
Y=dataset.iloc[:,1].values


from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,Y_train)

print(regressor.intercept_)
print(regressor.coef_)

y_pred=regressor.predict(X_test)
df=pd.DataFrame({'Actual':Y_test,'Predicted':y_pred})
df

from sklearn.metrics import r2_score

r2_score(Y_test, y_pred)